#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/Solar_Transport.jar:$APPDIR/lib/core.jar:$APPDIR/lib/toxiclibscore.jar:$APPDIR/lib/controlP5.jar" Solar_Transport
