#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/InjectImage.jar:$APPDIR/lib/core.jar:$APPDIR/lib/toxiclibscore.jar:$APPDIR/lib/verletphysics.jar:$APPDIR/lib/controlP5.jar" InjectImage
