#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/Solar_System.jar:$APPDIR/lib/core.jar:$APPDIR/lib/verletphysics.jar:$APPDIR/lib/toxiclibscore.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.jar" Solar_System
